[versions]
paperweight = "2.+"
paper = "1.21.10-R0.1-SNAPSHOT"
nimbus = "11.30.1"
luckperms = "5.4"

[libraries]
nimbus = { module = "com.nimbusds:oauth2-oidc-sdk", version.ref = "nimbus" }
luckperms = { module = "net.luckperms:api", version.ref = "luckperms" }

[plugins]
paperweight = { id = "io.papermc.paperweight.userdev", version.ref = "paperweight" }